# Generated by Django 4.1.5 on 2023-01-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_intraday_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='intraday',
            name='ticker',
            field=models.CharField(default='IBM', max_length=10),
            preserve_default=False,
        ),
    ]
