# Generated by Django 4.1.5 on 2023-01-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_adl_adx_aroon_bbp8_model_macd_obv_rsi_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adl',
            old_name='df',
            new_name='adl',
        ),
    ]
