# Generated by Django 4.1.5 on 2023-01-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_rename_df_adl_adl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='macd',
            old_name='time',
            new_name='date',
        ),
    ]
