# Generated by Django 4.1.5 on 2023-01-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_finnish_stock_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='finnish_stock_daily',
            name='average',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
