# Generated by Django 4.1.5 on 2023-01-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_alter_adl_date_alter_bbp8_model_date_alter_obv_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adx',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='aroon',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='macd',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rsi',
            name='date',
            field=models.DateField(),
        ),
    ]
