# Generated by Django 4.1.5 on 2023-01-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_alter_adx_date_alter_aroon_date_alter_macd_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsi',
            name='rsi',
            field=models.FloatField(null=True),
        ),
    ]
