# Generated by Django 4.1.5 on 2023-01-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_alter_rsi_rsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='optimal_buy_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('buy_point', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='optimal_sell_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('sell_point', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('period', models.IntegerField()),
                ('std_dev', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
