# Generated by Django 4.1.5 on 2023-01-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_optimal_buy_point_optimal_sell_point_sd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macd',
            name='macd',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='macd',
            name='macd_signal',
            field=models.FloatField(),
        ),
    ]
