# Generated by Django 4.1.5 on 2023-01-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_rename_optimal_buy_point_optimal_buy_sell_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optimal_buy_sell_points',
            old_name='buy_point',
            new_name='value',
        ),
        migrations.AddField(
            model_name='optimal_buy_sell_points',
            name='command',
            field=models.CharField(default='paska', max_length=10),
            preserve_default=False,
        ),
    ]
