# Generated by Django 4.1.5 on 2023-01-31 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_aroonoy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSIoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('period', models.IntegerField()),
                ('rsi', models.FloatField(null=True)),
                ('stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trading.finnish_stock_daily')),
            ],
        ),
    ]
