# Generated by Django 4.1.5 on 2023-02-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_remove_adl_stock_remove_adx_stock_remove_adxoy_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signals',
            old_name='rsi',
            new_name='rsi14',
        ),
        migrations.AddField(
            model_name='signals',
            name='rsi50',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='signals',
            name='rsi7',
            field=models.FloatField(null=True),
        ),
    ]
