# Generated by Django 4.1.5 on 2023-02-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0023_rename_rsi_signals_rsi14_signals_rsi50_signals_rsi7'),
    ]

    operations = [
        migrations.CreateModel(
            name='reverse_signals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('adl', models.FloatField(null=True)),
                ('obv', models.FloatField(null=True)),
                ('bbp8', models.FloatField(null=True)),
                ('adx', models.FloatField(null=True)),
                ('rsi5', models.FloatField(null=True)),
                ('rsi7', models.FloatField(null=True)),
                ('aroon_up', models.FloatField(null=True)),
                ('aroon_down', models.FloatField(null=True)),
                ('macd', models.FloatField(null=True)),
                ('macd_signal', models.FloatField(null=True)),
                ('std_dev', models.FloatField(null=True)),
                ('ema5', models.FloatField(null=True)),
                ('stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trading.finnish_stock_daily')),
            ],
        ),
    ]
