# Generated by Django 5.0.3 on 2024-03-10 14:03
from django.db import migrations
from django.db.models.indexes import Index
from django.db.migrations import AddIndex


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0025_remove_reverse_signals_aroon_down_and_more'),
    ]

    operations = [
        AddIndex(
            model_name='optimal_buy_sell_points',
            index=Index(fields=['stock'], name='optimal_buy_sell_stock_index')
        ),
        AddIndex(
            model_name='reverse_signals',
            index=Index(fields=['stock'], name='reverse_signals_stock_index')
        ),
    ]
