# Generated by Django 5.0.3 on 2024-03-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0026_auto_20240310_1403'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='optimal_buy_sell_points',
            name='optimal_buy_sell_stock_index',
        ),
        migrations.RemoveIndex(
            model_name='reverse_signals',
            name='reverse_signals_stock_index',
        ),
    ]
