class Stock:
    def __init__(self, symbol, company_name):
        self.symbol = symbol
        self.company_name = company_name


stocks = [
    Stock('ACG1V', 'Aspocomp Group Oyj ACG1V'),
    Stock('AFAGR', 'Afarak Group SE AFAGR'),
    Stock('AKTIA', 'Aktia Pankki Oyj AKTIA'),
    Stock('ALBAV', 'Ålandsbanken Abp A ALBAV'),
    Stock('ALBBV', 'Ålandsbanken Abp B ALBBV'),
    Stock('ALMA', 'Alma Media Oyj ALMA'),
    Stock('ANORA', 'Anora Group Oyj ANORA'),
    Stock('APETIT', 'Apetit Oyj APETIT'),
    Stock('ASPO', 'Aspo Oyj ASPO'),
    Stock('ATRAV', 'Atria Oyj A ATRAV'),
    Stock('BIOBV', 'Biohit Oyj BIOBV'),
    Stock('BITTI', 'Bittium Oyj BITTI'),
    Stock('BOREO', 'Boreo Oyj BOREO'),
    Stock('CAPMAN', 'CapMan Oyj CAPMAN'),
    Stock('CAV1V', 'Caverion Oyj CAV1V'),
    Stock('CGCBV', 'Cargotec Oyj CGCBV'),
    Stock('CONSTI', 'Consti Oyj CONSTI'),
    Stock('CTH1V', 'Componenta Oyj CTH1V'),
    Stock('CTY1S', 'Citycon Oyj CTS1V'),
    Stock('DIGIA', 'Digia Oyj DIGIA'),
    Stock('DIGIGR', 'Digitalist Group Oyj DIGIGR'),
    Stock('DOV1V', 'Dovre Group Oyj DOV1V'),
    Stock('EEZY', 'Eezy Oyj EEZY'),
    Stock('ELEAV', 'Elecster Oyj A ELEAV'),
    Stock('ELISA', 'Elisa Oyj ELISA'),
    Stock('ENENTO', 'Enento Group Oyj ENENTO'),
    Stock('EQV1V', 'eQ Oyj EQV1V'),
    Stock('ERIBR', 'Telefonaktiebolaget LM Ericsson (publ) ERIBR'),
    Stock('ESENSE', 'Enersense International Oyj ESENSE'),
    Stock('ETTE', 'Etteplan Oyj ETTE'),
    Stock('EVLI', 'Evli Pankki Oyj EVLI'),
    Stock('EXL1V', 'Exel Composites Oyj EXL1V'),
    Stock('FORTUM', 'Fortum Oyj FORTUM'),
    Stock('FSECURE', 'F-Secure Oyj FSECURE'),
    Stock('FSKRS', 'Fiskars Oyj Abp FSKRS'),
    Stock('GLA1V', 'Glaston Oyj Abp GLA1V'),
    Stock('GOFORE', 'Gofore Oyj GOFORE'),
    Stock('HARVIA', 'Harvia Oyj HARVIA'),
    Stock('HKSAV', 'HKScan Oyj A HKSAV'),
    Stock('HONBS', 'Honkarakenne Oyj HONBS'),
    Stock('HUH1V', 'Huhtamäki Oyj HUH1V'),
    Stock('ICP1V', 'Incap Oyj ICP1V'),
    Stock('IFA1V', 'Innofactor Oyj IFA1V'),
    Stock('ILKKA1', 'Ilkka Oyj 1 ILKKA1'),
    Stock('ILKKA2', 'Ilkka Oyj 2 ILKKA2'),
    Stock('INVEST', 'Investors House Oyj INVEST'),
    Stock('KAMUX', 'Kamux Oyj KAMUX'),
    Stock('KCR', 'Konecranes Oyj KCR'),
    Stock('KELAS', 'Kesla Oyj A KELAS'),
    Stock('KEMIRA', 'Kemira Oyj KEMIRA'),
    Stock('KESKOA', 'Kesko Oyj A KESKOA'),
    Stock('KESKOB', 'Kesko Oyj B KESKOB'),
    Stock('KHG', 'KH Group Oyj KHG'),
    Stock('KNEBV', 'KONE Oyj KNEBV'),
    Stock('KOJAMO', 'Kojamo Oyj KOJAMO'),
    Stock('KOSKI', 'Koskisen Oyj KOSKI'),
    Stock('KREATE', 'Kreate Group Oyj KREATE'),
    Stock('KSLAV', 'Keskisuomalainen Oyj KSLAV'),
    Stock('LAMOR', 'Lamor Corporation Oyj LAMOR'),
    Stock('LAT1V', 'Lassila & Tikanoja Oyj LAT1V'),
    Stock('LINDEX', 'Lindex Group Oyj LINDEX'),
    Stock('MANTA', 'Mandatum Oyj MANTA'),
    Stock('MARAS', 'Martela Oyj MARAS'),
    Stock('MEKKO', 'Marimekko Oyj MEKKO'),
    Stock('METSA', 'Metsä Board Oyj A METSA'),
    Stock('METSB', 'Metsä Board Oyj B METSB'),
    Stock('METSO', 'Metso Outotec Oyj METSO'),
    Stock('MUSTI', 'Musti Group Oyj MUSTI'),
    Stock('NDA', 'Nordea Bank Abp NDA'),
    Stock('NESTE', 'Neste Oyj NESTE'),
    Stock('NLG1V', 'Nurminen Logistics Oyj NLG1V'),
    Stock('NOHO', 'NoHo Partners Oyj NOHO'),
    Stock('NOKIA', 'Nokia Oyj NOKIA'),
    Stock('OKDAV', 'Oriola Oyj A OKDAV'),
    Stock('OKDBV', 'Oriola Oyj B OKDBV'),
    Stock('OLVAS', 'Olvi Oyj Series A  OLVAS'),
    Stock('OMASP', 'Oma Säästöpankki Oyj OMASP'),
    Stock('OPTOMED', 'Optomed Oyj OPTOMED'),
    Stock('ORNAV', 'Orion Oyj A ORNAV'),
    Stock('ORNBV', 'Orion Oyj B ORNBV'),
    Stock('ORTHEX', 'Orthex Oyj ORTHEX'),
    Stock('OUT1V', 'Outokumpu Oyj OUT1V'),
    Stock('OVARO', 'Ovaro Kiinteistösijoitus Oyj OVARO'),
    Stock('PAMPALO', 'Endomines Finland Oyj PAMPALO'),
    Stock('PIHLIS', 'Pihlajalinna Oyj PIHLIS'),
    Stock('PNA1V', 'Panostaja Oyj PNA1V'),
    Stock('PON1V', 'Ponsse Oyj PON1V'),
    Stock('PUMU', 'PunaMusta Media Oyj PUMU'),
    Stock('PURMO', 'Purmo Group Oyj PURMO'),
    Stock('PUUILO', 'Puuilo Oy PUUILO'),
    Stock('QPR1V', 'QPR Software Oyj QPR1V'),
    Stock('QTCOM', 'QT Group Oyj QTCOM'),
    Stock('RAIKV', 'Raisio Oyj K RAIKV'),
    Stock('RAIVV', 'Raisio Oyj Vaihto-osake RAIVV'),
    Stock('RAP1V', 'Rapala VMC Oyj RAP1V'),
    Stock('RAUTE', 'Raute Oyj RAUTE'),
    Stock('REG1V', 'Revenio Group Oyj REG1V'),
    Stock('REKA', 'Reka Industrial Oyj REKA'),
    Stock('RELAIS', 'Relais Group Plc RELAIS'),
    Stock('REMEDY', 'Remedy Entertainment Oyj REMEDY'),
    Stock('ROBIT', 'Robit Oyj ROBIT'),
    Stock('SAGCV', 'Saga Furs Oyj SAGCV'),
    Stock('SAMPO', 'Sampo Oyj SAMPO'),
    Stock('SANOMA', 'Sanoma Oyj SANOMA'),
    Stock('SCANFL', 'Scanfil Oyj SCANFL'),
    Stock('SIILI', 'Siili Solutions Oyj SIILI'),
    Stock('SITOWS', 'Sitowise Group Oyj SITOWS'),
    Stock('SOLTEQ', 'Solteq Oyj SOLTEQ'),
    Stock('SOSI1', 'Sotkamo Silver AB SOSI1'),
    Stock('SRV1V', 'SRV Group Plc SRV1V'),
    Stock('SSABAH', 'SSAB AB A SSABAH'),
    Stock('SSABBH', 'SSAB AB B SSABBH'),
    Stock('SSH1V', 'SSH Communications Security Oyj SSH1V'),
    Stock('STEAV', 'Stora Enso Oyj A STEAV'),
    Stock('STERV', 'Stora Enso Oyj R STERV'),
    Stock('SUY1V', 'Suominen Oyj SUY1V'),
    Stock('TAALA', 'Taaleri Oyj TAALA'),
    Stock('TALLINK', 'Tallink Grupp AS TALLINK'),
    Stock('TELIA1', 'Telia Company AB TELIA1'),
    Stock('TEM1V', 'Tecnotree Oyj TEM1V'),
    Stock('TIETO', 'TietoEVRY Oyj TIETO'),
    Stock('TLT1V', 'Teleste Oyj TLT1V'),
    Stock('TNOM', 'Talenom Oyj TNOM'),
    Stock('TOKMAN', 'Tokmanni Group Oyj TOKMAN'),
    Stock('TRH1V', 'Trainers House TRH1V'),
    Stock('TTALO', 'Terveystalo Oyj TTALO'),
    Stock('TULAV', 'Tulikivi Oyj A TULAV'),
    Stock('TYRES', 'Nokian Renkaat Oyj TYRES'),
    Stock('UNITED', 'United Bankers Oyj UNITED'),
    Stock('UPM', 'UPM-Kymmene Oyj UPM'),
    Stock('UPONOR', 'Uponor Oyj UPONOR'),
    Stock('VAIAS', 'Vaisala Oyj VAIAS'),
    Stock('VALMT', 'Valmet Oyj VALMT'),
    Stock('VERK', 'Verkkokauppa.com Oyj VERK'),
    Stock('VIK1V', 'Viking Line Abp VIK1V'),
    Stock('WETTERI', 'Wetteri Power Oy WETTERI'),
    Stock('WITH', 'WithSecure WITH'),
    Stock('WRT1V', 'Wärtsilä Oyj WRT1V'),
    Stock('WUF1V', 'Wulff-Yhtiöt Oyj WUF1V'),
    Stock('YIT', 'YIT Oyj YIT')
    ]

stock_dict = {stock.symbol: stock for stock in stocks}


def real_names_list(stock_list):
    real_names = []
    for item in stock_list:
        symbol = item['symbol']
        stock = stock_dict[symbol]
        real_names.append(stock)
    return real_names


def real_names_list_without_symbol(stock_list):
    real_names = []
    for symbol in stock_list:
        stock = stock_dict[symbol]
        real_names.append(stock.company_name)
    return real_names
